x=int(input("nhập giá trị x: "))
y=int(input("nhập giá trị y: "))
z=int(input("nhập giá trị z: "))
t=int(input("nhập giá trị t: "))
print("giá trị lớn nhất trong các số trên là: ",max(x,y,z,t))
print("giá trị nhỏ nhất trong các số trên là: ",min(x,y,z,t) )